//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Receiver table
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "receiver")]
pub struct Model {
    /// Primary key
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing, skip_serializing)]
    pub id: u32,
    /// Name
    pub name: String,
    /// Public key
    pub address: String,
    /// Network
    pub network: u32,
    /// Nonce
    pub nonce: u32,
    /// Created date
    #[serde(skip_deserializing)]
    pub created_date: String,
}

/// Receiver related columns
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// Relation between receiver and randomness
    #[sea_orm(has_many = "super::randomness::Entity")]
    Randomness,
}

impl Related<super::randomness::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Randomness.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
