//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "randomness")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub keyring_id: i64,
    pub receiver_id: i64,
    pub epoch: i64,
    #[sea_orm(unique)]
    pub alpha: String,
    pub gamma: String,
    pub c: String,
    pub s: String,
    #[sea_orm(unique)]
    pub y: String,
    pub witness_address: String,
    pub witness_gamma: String,
    pub witness_hash: String,
    pub inverse_z: String,
    #[sea_orm(unique)]
    pub signature_proof: String,
    pub created_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::keyring::Entity",
        from = "Column::KeyringId",
        to = "super::keyring::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Keyring,
    #[sea_orm(
        belongs_to = "super::receiver::Entity",
        from = "Column::ReceiverId",
        to = "super::receiver::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Receiver,
}

impl Related<super::keyring::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Keyring.def()
    }
}

impl Related<super::receiver::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Receiver.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
